AllCops:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'tmp/**/*'
    - 'Gemfile'

Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  IgnoreCopDirectives: true
  IgnoredPatterns:
    - '^#.*'
  Enabled: true

Style/EmptyMethod:
  Enabled: false

Style/StringLiterals:
  Enabled: false
